# Generated by Django 4.2.1 on 2023-07-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='user',
            new_name='user_id',
        ),
    ]
