# Generated by Django 4.2.1 on 2023-07-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_user_newsarticle_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='user_id',
            new_name='user',
        ),
    ]
