# Generated by Django 4.2.1 on 2023-07-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_newsarticle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='user',
        ),
    ]
