# Generated by Django 4.2.1 on 2023-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_user_id_newsarticle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
