# Generated by Django 4.2.1 on 2023-07-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_newsarticle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=100000),
        ),
    ]
