# Generated by Django 4.2.1 on 2023-07-17 16:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_newsarticle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='headline', unique=True),
        ),
    ]
