# Generated by Django 4.2.1 on 2023-07-17 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_newsarticle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('restaurant', 'Restaurant'), ('drink', 'Drink')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
