# Generated by Django 4.2.1 on 2023-07-17 17:33

import Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to=Login.models.get_image_upload_path),
        ),
    ]
